### ISSUE TITLE
Error using previous database.db

### ISSUE THREAD

**Issue by martinglass** [pulquero/RotorHazard#30]
using BetaHazard on 1st June 2021, I encountered this log error when inserting the previous RH-main database...

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: pilot.url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/RotorHazard/src/server/server.py", line 4920, in <module>
    init_race_state()
  File "/home/pi/RotorHazard/src/server/server.py", line 4341, in init_race_state
    RACE.node_teams[heatNode.node_index] = RHData.get_pilot(heatNode.pilot_id).team
  File "/home/pi/RotorHazard/src/server/RHData.py", line 493, in get_pilot
    return self._Database.Pilot.query.get(pilot_id)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: pilot.url
[SQL: SELECT pilot.id AS pilot_id, pilot.callsign AS pilot_callsign, pilot.team AS pilot_team, pilot.phonetic AS pilot_phonetic, pilot.name AS pilot_name, pilot.color AS pilot_color, pilot.url AS pilot_url 
FROM pilot 
WHERE pilot.id = ?]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/13/e3q8

**Comment by pulquero** [comment]
Please verify fix in https://github.com/pulquero/RotorHazard/pull/31.

**Comment by pulquero** [comment]
Fixed and merged.
