### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Aaronsss** [pulquero/RotorHazard#50]
I am not sure if I am just being a noob but when trying to start the server on the 6 node Bpill I get the following error:

pi@LapTimer:~/RotorHazard_Beta/src $ python3 -m server.server
server [WARNING] No configuration file found, using defaults
__main__ [INFO] RotorHazard v3.1.0-dev.7
__main__ [INFO] Release: 3.1.0-dev.7 / Server API: 33 / Latest Node API: 35
server.RHUtils [INFO] Host machine: Raspberry Pi 3 Model B Rev 1.2
server.RHUtils [INFO] Host OS: Linux 5.10.52-v7+
server.RHUtils [INFO] Python version: 3.7.3
__main__ [INFO] Host machine is 'LapTimer' at 192.168.1.120
__main__ [INFO] Using log file: logs/rh_20210731_170420.log
interface.Plugins [INFO] Loaded module i2c_helper
__main__ [INFO] Unable to initialize nodes via interface.RHInterface:  No module named 'numpy'
__main__ [ERROR] Error initializing hardware interface
Traceback (most recent call last):
  File "/home/pi/RotorHazard_Beta/src/server/server.py", line 4819, in initialize_hardware_interface
    interfaceModule = importlib.import_module('interface.MockInterface')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/RotorHazard_Beta/src/interface/MockInterface.py", line 10, in <module>
    from .RHInterface import TIMER_MODE, SCANNER_MODE, RSSI_HISTORY_MODE
  File "/home/pi/RotorHazard_Beta/src/interface/RHInterface.py", line 11, in <module>
    from interface import persistent_homology as ph
  File "/home/pi/RotorHazard_Beta/src/interface/persistent_homology.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by pulquero** [comment]
You need to run install.sh, numpy needs to be installed via apt, not pip.
