### ISSUE TITLE
Bug Report: In LapRF branch

### ISSUE THREAD

**Issue by martinglass** [pulquero/RotorHazard#53]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/martin/Downloads/Delta5 RotorHazard PIDflight ImmersionRC etc racetimers/RotorHazard/RotorHazard-laprf/src/tests/test_laprf_protocol.py", line 2, in <module>
    from interface.laprf_protocol import SOR, EOR, ESC, ESC_OFFSET
  File "interface/__init__.py", line 37
    def calculate_checksum(data: bytearray):
                               ^
SyntaxError: invalid syntax

**Comment by pulquero** [comment]
python 2 is not supported.

**Comment by martinglass** [comment]
Ooops. Sorry!
